### ISSUE TITLE
Emulation and testing

### ISSUE THREAD

**Issue by neauoire** [marcpaq/arpilisp#5]
Hi Marc,

This is a superb project, and it works quite as intended, so this is more of a question than an issue.

I would like to use experiment with arpilisp on a MacBook, I was wondering what would have to be changed so gcc can compile this for non ARM devices. Is there a simple way to run this over qemu?

Basically, I'm curious as to how you went about building this, I can't imagine that you were flashing your pi at every change.

Thank you 👍

**Comment by marcpaq** [comment]
Hi,

Thanks, I'm happy you like it.

Good question. I'm not familiar with qemu but if it supports ARMv6 emulation that is capable of running a Linux distro then you should be good to go.

You can adapt arpilisp to not even require that. It uses only 3 kernel system calls and a fixed amount of memory, so there isn't much to modify to use other kernels or even bare metal. In this case, in theory, all you need is an assembler that targets ARMv6 and a tool to load/flash your binary.

I developed arpilisp on Raspbian, which runs on the Raspberry Pi. I didn't have to flash my Pi since Raspbian is a full GNU/Linux distribution. My tools: gcc & gdb (running on Raspbian), ssh & emacs (running on my desktop).

Good luck with your project. What do you intend to use it for? Let me know how it goes.

Marc.

**Comment by neauoire** [comment]
Since my message I got it to build on OSX properly, I'm still new to this kind of things and I guess I just didn't quite understood how qemu actually worked.

Well, I have this silly dream of turning an [old game of mine](
http://wiki.xxiivv.com/paradise) into a microkernel. I've been rebuilding it in LISP and am hoping to spin a sort of rpi distro, it's still kind of a blur, but I'm doing some research at the moment, to see how little I need to get a lisp interpreter going and running. — So, your project falls exactly in the gap of tech that was missing from the puzzle :)

**Comment by marcpaq** [comment]
That's pretty cool. 

If it helps, take a look at my list of other simple language implementations. You might find something more suitable than arpilisp or, at least, some inspiration: https://github.com/marcpaq/b1fipl

Good luck!

**Comment by neauoire** [comment]
That's amazing, I hadn't seen this before.
Thank you :)
